# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc7fd4d731e64919fd8af1a398d2b76445749d2a5b5ae225cbb8d18f6accc682aa99d8af103702a1e513a8aedb1c5bdfaa248a4a94c164e11802d2453d9b16cd

test:
  secret_key_base: c4be415ebab00413844668771cb6f217dacbe88db807e8da64ac248a473065de181f59397754f4f39c0396f0a6d243d8f0a68e3fa0c5a474a52bab8b4d442ace

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
